<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>false</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ProjectOdyssey.Tests\**" />
    <EmbeddedResource Remove="ProjectOdyssey.Tests\**" />
    <None Remove="ProjectOdyssey.Tests\**" />
	<None Include="test charts\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="StbImageSharp" Version="2.30.16" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="engine\EventBus.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="engine\GameClock.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="engine\GameSession.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="engine\Judgement.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="engine\JudgementEngine.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="engine\Note.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="engine\Result.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="input\InputEvent.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="input\InputHistory.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="input\RawInputStructs.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="input\Win32KeyInputListener.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="input\Win32RawInputMethods.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="render\GameplayRenderer.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="render\Renderer.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="render\Shader.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="render\Texture.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="screens\GameplayScreen.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="screens\IGameScreen.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="charts\test_single_long_note.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="shader\shader.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="shader\shader.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\judgement_line.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\ln_body.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\ln_head_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\ln_head_2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\ln_head_3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\ln_head_4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\ln_head_5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\ln_head_6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\ln_head_7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\ln_tail.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\receptor_down.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\receptor_up.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="skins\Skin 1\tap_note_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="test charts\Ibuki Kido &amp; Erii Yamazaki - pupa (TV Size) (MapleSyrup-) [Metamorphosis].osu">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="charts\" />
    <Folder Include="skins\Skin 1\" />
  </ItemGroup>

</Project>
